apiVersion: apps/v1
kind: Deployment
metadata:
  name: real-esrgan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: real-esrgan
  template:
    metadata:
      labels:
        app: real-esrgan
    spec:
      containers:
        - name: real-esrgan
          image: r8.im/nightmareai/real-esrgan@sha256:350d32041630ffbe63c8352783a26d94126809164e54085352f8326e53999085
          ports:
            - containerPort: 5000
          resources:
            limits:
              memory: "8Gi"
              cpu: "4"
            requests:
              memory: "4Gi"
              cpu: "2"
---
apiVersion: v1
kind: Service
metadata:
  name: real-esrgan
spec:
  type: LoadBalancer
  ports:
    - port: 5001
      targetPort: 5000
  selector:
    app: real-esrgan
